food/urls.py
from . import views
from django.urls import path

app_name = 'food'
urlpatterns = [
    #/food/
    path('', views.index, name='index'),
    path('<int:item_id>/', views.detail, name='detail'),
    path('item/', views.item, name='item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
]

food/models.py
from django.db import models

# Create your models here.

class Item(models.Model):

    def __str__(self):
        return self.item_name

    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price =models.IntegerField()
    item_image = models.CharField(max_length=500, default="https://static.vecteezy.com/system/resources/previews/003/170/825/original/isolated-food-plate-fork-and-spoon-design-free-vector.jpg")

food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from django.template import loader

# Create your views here.

def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list': item_list,
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'food/index.html', context)

def item(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request, item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item': item,
    }
    return render(request, 'food/detail.html', context)

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar bg-primary">
        <a href="#" class="navbar-brand">FoodApp</a>
        <div class="navbar">
            <a class="nav-item nav-link" href="#">Menu Item-- </a>
            <a class="nav-item nav-link" href="#">Delete Item--</a>
            <a class="nav-item nav-link" href="#">View Item</a>                        
        </div>
    </nav>
    {% block body %}    
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_image }}" class="card-img img-fluid" style="max-height: 200px;" />
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>{{ item.item_price }}</h3>
        </div>
    </div>
</div>

{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
</head>
<body>

    {% block body %}    
    {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">

                <img src="{{ item.item_image }}" class="card-img img-fluid" style="max-height: 200px;" />
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>{{ item.item_price }} €</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>

    {% endfor %}
    {% endblock %}

</body>
</html>